[server]
fileWatcherType = "poll"


SUPABASE_URL = "https://bfxpqmkhwgdsyvzzxnjk.supabase.co"
SUPABASE_KEY = "sb_publishable_9q666dvsL09qnBjhxOvYvg_IvKrrctf"
ANTHROPIC_API_KEY = "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"
